#!/bin/bash

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
CMD="problog -L $scriptdir/../model/"

usage () {
    echo "USAGE: run_test TESTFILE"
    exit 1
}

if (( $# != 1 )); then
    usage
fi

$CMD --timeout 3 $1
