#!/bin/bash

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
CMD="problog -L $scriptdir/../include/"

usage () {
    echo "USAGE: run_test TESTFILE"
    exit 1
}

if (( $# != 1 )); then
    usage
fi

timeout -s SIGINT --preserve-status 3.0s $CMD $1
