#!/bin/bash

scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

pl_CMD="problog -L $scriptdir/../model/"
pl_testfiles="$(ls "$scriptdir"/test_*.pl)"
py_CMD="python -m unittest"
py_testfiles="$(ls "$scriptdir"/test_*.py)"

# colors
# https://gist.github.com/elucify/c7ccfee9f13b42f11f81
RESTORE=$(echo -en '\033[0m')
RED=$(echo -en '\033[00;31m')
GREEN=$(echo -en '\033[00;32m')

PASS="$GREEN[PASS ]$RESTORE"
FAIL="$RED[FAIL ]$RESTORE"
ERROR="$RED[ERROR]$RESTORE"

print_result () {
    test=$1
    status=$2
    output=$3
    if (( $status != 0 )); then
        echo $ERROR $test
        return
    fi
    failed_num=$(echo "$result" | grep "\s*0\s*$" | wc -l)
    if (( $failed_num > 0 )); then
        echo $FAIL $test
        return
    fi
    echo $PASS $test
}

# run prolog tests
for test in $pl_testfiles
do
    result=$($pl_CMD --timeout 3 $test)
    status=$(echo $?)
    print_result $test $status $result
done

# run python tests
for test in $py_testfiles
do
    result=$(cd $scriptdir/..; $py_CMD $test 2> /dev/null)
    status=$(echo $?)
    print_result $test $status $result
done
